apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build
spec:
  params:
  - name: git-url
    value: 'https://github.com/quay/quay'
  - name: git-revision
    value: refs/pull/{{PR_NUMBER}}/head
  - name: image
    value: 'image-registry.openshift-image-registry.svc:5000/obulatov-test/quay'
  pipelineRef:
    name: build
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
