apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: run-quay
  namespace: run-quay
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
  to:
    name: run-quay
