apiVersion: v1
data:
  create-extensions.sh: |
    #!/bin/sh -eu
    psql --set ON_ERROR_STOP=1 -d quay <<EOF
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    EOF
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: quay-postgresql-postgresql-start
