apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build
spec:
  workspaces:
  - name: shared-workspace
  - name: manifests
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
  - name: image
    type: string
    description: image to be build from the code
  - name: namespace
    type: string
    description: the current namespace
  - name: hostname
    type: string
    description: the hostname that should be used by Quay
  tasks:
  - name: deploy-dependencies
    taskRef:
      name: deploy-dependencies
      kind: Task
    workspaces:
    - name: manifests
      workspace: manifests
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-image
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.image)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  - name: deploy-quay-app
    taskRef:
      name: deploy-quay-app
      kind: Task
    workspaces:
    - name: manifests
      workspace: manifests
    params:
    - name: namespace
      value: $(params.namespace)
    - name: hostname
      value: $(params.hostname)
    runAfter:
    - deploy-dependencies
    - build-image
