apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-dependencies
spec:
  workspaces:
  - name: manifests
  steps:
  - name: apply
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    workingDir: /workspace/manifests
    command: ["/bin/bash", "-c"]
    args:
    - |
      cat ./quay-postgresql.yaml ./quay-redis.yaml ./route.yaml | oc apply -f -
