---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-app
  annotations:
    app.openshift.io/connects-to: |
      [
        {"apiVersion":"apps/v1","kind":"Deployment","name":"quay-redis"},
        {"apiVersion":"apps/v1","kind":"Deployment","name":"quay-postgresql"}
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quay-app
  template:
    metadata:
      labels:
        app: quay-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/quay:latest
        name: quay
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 40m
            memory: 2600Mi
        volumeMounts:
        - name: config
          mountPath: /quay-registry/conf/stack
      volumes:
      - name: config
        secret:
          secretName: quay-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: quay-app
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: quay-app
